title: Chen Fang

# tagline: Here is personal website of Hanlin Cai. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly

url: https://charlie-pku.github.io/

# Owner/author information
owner:
  name: Chen Fang
  avatar: dengfeng_2023.jpg
  # bio: Two roads diverged in woods, I took the one less traveled by.
  email: charlie_pku@outlook.com
  cv: https://charlie-pku.github.io/file/CV_2024.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: Charlie_Fang_
  github: Charlie-PKU
  linkedin: fc-charlie
  scholar: https://scholar.google.com.hk/citations?user=EugWJzkAAAAJ&hl=zh-CN
  bilibili: 37318097
  researchgate: https://www.researchgate.net/profile/Chen-Fang-37
  zhihu: https://www.zhihu.com/people/fang-chen-41-97
  instagram: charliebrown_0920

  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
# google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Research
    url: /research/
  # - title: Publication
  #   url: /publications/
  - title: Activity
    url: /activities/
  # - title: Hobbies
  #   url: /hobbies/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Chongqing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: Charlie

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/12/10 by Hanlin Cai.